# Generated by Django 2.2 on 2019-11-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_goods_urllist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urllist',
            options={},
        ),
        migrations.AddField(
            model_name='goods',
            name='pic_index',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='urllist',
            table='pics',
        ),
    ]
