# Generated by Django 2.2 on 2019-11-05 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191105_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urllist',
            name='goods',
        ),
        migrations.AddField(
            model_name='goods',
            name='urls',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.UrlList', verbose_name='学生'),
        ),
    ]
