# Generated by Django 2.2 on 2019-11-05 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191105_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='attn_status',
            new_name='category',
        ),
    ]
