# Generated by Django 2.2 on 2019-12-08 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191105_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='urls',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.UrlList', verbose_name='urls'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.OAuthConfig', verbose_name='用户'),
        ),
    ]
