# Generated by Django 2.2 on 2019-12-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191208_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='category',
            field=models.CharField(choices=[('0', '正常'), ('3', '迟到'), ('1', '请假'), ('2', '审核中'), ('4', '早退'), ('5', '旷课'), ('6', '假期')], default='0', max_length=1, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='detail',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='详情介绍'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='pic_index',
            field=models.TextField(blank=True, null=True, verbose_name='标题图'),
        ),
    ]
