# Generated by Django 2.2 on 2019-12-08 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20191208_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.OAuthUser', verbose_name='用户'),
        ),
    ]
